# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(default='False', max_length=5)),
                ('type_message', models.CharField(choices=[('QUESTION', 'QUESTION'), ('SUGGESTION', 'SUGGESTION')], default='QUESTION', max_length=10)),
            ],
        ),
    ]
